# Generated by Django 6.0.3 on 2026-03-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "Book_title",
                    models.CharField(max_length=30, verbose_name="Title of the book"),
                ),
                ("published", models.DateField()),
            ],
        ),
    ]
