# Generated by Django 6.0.3 on 2026-03-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="books/covers/"),
        ),
        migrations.AddField(
            model_name="book",
            name="manuscript",
            field=models.FileField(
                blank=True, null=True, upload_to="books/manuscripts/"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="summary",
            field=models.TextField(
                blank=True, help_text="A short story about the story"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="published",
            field=models.DateField(auto_now_add=True),
        ),
    ]
