# Generated by Django 6.0.3 on 2026-03-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "webapp",
            "0002_book_cover_book_manuscript_book_summary_book_updated_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(default="John", max_length=80),
        ),
        migrations.AddField(
            model_name="book",
            name="author_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="book",
            name="pages",
            field=models.CharField(default=8, max_length=80),
        ),
        migrations.AlterField(
            model_name="book",
            name="manuscript",
            field=models.FileField(upload_to="books/manuscripts/"),
        ),
    ]
